[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  
# Handle specific error pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/error"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"